### PR TITLE
Add support for Bolt Protocol

### PR DESCRIPTION
**Pull request by ducky427**
WIP. Please do not merge!

Creating this PR so that the code is tested on Travis.

### CODE REVIEW

**Comment by ducky427** [comment]
@jexp, I think I've covered most of the API. Am I missing anything? 

Thanks.

**Comment by michaelklishin** [comment]
@ducky427 what's the status of this?

**Comment by michaelklishin** [comment]
@ducky427 hey, should we merge this?

**Comment by ducky427** [comment]
@michaelklishin, sorry about leaving this dangling for such a long time. let me circle back to this.

**Comment by tuddman** [comment]
pushing a `3.2.0` release with these bolt changes to maven / clojars would be most appreciated as well!

**Comment by michaelklishin** [comment]
@ducky427 no worries. @tuddman we will try :)

**Comment by tuddman** [comment]
@michaelklishin @ducky427 

In the kindest possible tone:  any chance this can be merged and pushed?  

I've been using a forked `3.2.0` version (includes `bolt`) in production for awhile now, & we have a number of automated builds that would be easier to deploy if they could pull this `neocons` from maven directly as well.

conflict is around supporting the latest version(s) of clojure. a quick fix.

**Comment by michaelklishin** [comment]
@tuddman I can add you as a collaborator so that you can polish this branch and then I'll merge it (and release a preview). How does that sound?

**Comment by tuddman** [comment]
sure! works for me.   Clojure + Neo4j are becoming my preferred wheelhouse anyway. happy to help :)

**Comment by tuddman** [comment]
@michaelklishin @ducky427 
resolved the conflicts.  if there's anything else you see that needs polishing before merging, let me know.

**Comment by michaelklishin** [comment]
@tuddman thank you! I think the best way to test and polish the new API is to have more people use it. I will cut a preview release tomorrow.

**Pull request merged**
