### PR TITLE
Neo4j 2.2 Support

### PR DESCRIPTION
**Pull request by ducky427**
Neo4j 2.2 adds an API for [Authentication & Authorization](http://neo4j.com/docs/2.2.0-RC01/rest-api-security.html). It used basic http-auth parameters for this which was already implemented by Neocons.

My changes:

- Fixed failing tests: Some of the test depended on the return order of some queries. 
- Added a method for resetting the default password: Neo4j Server by default has auth turned on and the user has to change the default password before doing anything. I've implemented a basic password changing function. NOTE: I've decided not to implement the whole auth API as most of the time people who use the library should already have a valid username and password.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you.

Sorry to nitpick but can we rename `password` to `passwords` in the ns? We tend to use plurals in Neocons and other ClojureWerkz projects.

**Comment by ducky427** [comment]
I've renamed the file @michaelklishin

**Comment by michaelklishin** [comment]
:+1:

**Comment by ducky427** [comment]
Thanks!

**Pull request merged**
