### PR TITLE
Drop Urly dependency

### PR DESCRIPTION
**Pull request by ricardojmendez**
I've removed the dependency on urly discussed on issue 69.

### CODE REVIEW

**Comment by michaelklishin** [comment]
CI failures seem related to the change. Please investigate and make sure you don't introduce more changes not related to Urly.

**Comment by ricardojmendez** [comment]
I'll review it, but lein all test passed here after a lein clean.

**Comment by ricardojmendez** [comment]
Bit at a loss here - all tests pass locally. As you can see on the commit, the only changes are the urly removal and adding two IntelliJ files to the .gitignore.   I've also just brought in the encode-path tests (something I initially forgot to do) and they pass as expected.

Will review further.

**Comment by michaelklishin** [comment]
All I can say right now is that CI passes on 464080b9837e31dd66fa2fc5fba067ec74fdc5fc.

**Comment by ducky427** [comment]
Looks like the graphene tests are failing. Seems that some environment variables for graphene are missing when these tests were run.

**Comment by ducky427** [comment]
It seems that I had marked the graphene variables as secure. So they are not available in the forks. Doc [here](http://docs.travis-ci.com/user/environment-variables/).

Should we disable those tests or is there a work around?

**Comment by michaelklishin** [comment]
Thank you @ricardojmendez and @ducky427!

**Comment by ricardojmendez** [comment]
Formidable, glad that's sorted.

**Comment by ducky427** [comment]
:+1:

**Pull request merged**
